export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const USER_METADATA_REPOSITORY = Symbol('USER_METADATA_REPOSITORY');
export const S3_SERVICE = Symbol('S3_SERVICE');

export const CREATE_USER_SERVICE = Symbol('CREATE_USER_SERVICE');
export const LIST_USERS_SERVICE = Symbol('LIST_USERS_SERVICE');

export const LIST_USERS_WITH_METADATA_SERVICE = Symbol(
  'LIST_USERS_WITH_METADATA_SERVICE',
);
